# Run with cmake -DTEST_DIR=<new temporary directory> -P this-file.
cmake_minimum_required(VERSION 3.21)
if(NOT TEST_DIR OR EXISTS "${TEST_DIR}")
  message(FATAL_ERROR "TEST_DIR must name a new temporary directory")
endif()
set(CMAKE_BINARY_DIR "${TEST_DIR}")
include("${CMAKE_CURRENT_LIST_DIR}/../CamadaDependencies.cmake")

# Replace downloads/builds, retaining the real migration and stamp logic.
function(camada_setup_shared_cadical)
  file(WRITE "${CAMADA_CADICAL_LIB}" "shared")
endfunction()
function(camada_build_bitwuzla_from_source prefix)
  if(EXISTS "${TEST_DIR}/bitwuzla-built")
    message(FATAL_ERROR "Current Bitwuzla was rebuilt")
  endif()
  file(WRITE "${TEST_DIR}/bitwuzla-built" "")
endfunction()
function(camada_fetch_git_source name repo tag out)
  if(EXISTS "${TEST_DIR}/cms-built")
    message(FATAL_ERROR "Current CMS was rebuilt")
  endif()
  foreach(old cadical cadiback cryptominisat_cadiback-src)
    if(EXISTS "${CMAKE_BINARY_DIR}/_deps/${old}")
      message(FATAL_ERROR "Stale ${old} was retained")
    endif()
  endforeach()
  set(${out}
      "${CMAKE_BINARY_DIR}/_deps/cryptominisat-src"
      PARENT_SCOPE)
endfunction()
function(camada_setup_cryptominisat_solver_deps source)
  file(WRITE "${CMAKE_BINARY_DIR}/_deps/cadiback/libcadiback.a" "new")
endfunction()
function(camada_run_checked)
  file(WRITE "${TEST_DIR}/cms-built" "")
  file(WRITE "${cms_config}" "")
  file(
    WRITE
    "${CAMADA_DEPS_INSTALL_DIR}/lib/cmake/cryptominisat5/cryptominisat5Targets.cmake"
    "")
endfunction()

# A prebuilt header must not bypass rebuilding, and the second call must reuse
# it.
file(WRITE "${CAMADA_DEPS_INSTALL_DIR}/include/bitwuzla/c/bitwuzla.h" "")
camada_setup_bitwuzla()
if(NOT EXISTS "${TEST_DIR}/bitwuzla-built")
  message(FATAL_ERROR "Prebuilt Bitwuzla was reused")
endif()
camada_setup_bitwuzla()

# Existing STP must still migrate its old CMS/CadiBack installation.
set(cms_dir "${CAMADA_DEPS_INSTALL_DIR}/lib/cmake/cryptominisat5")
file(WRITE "${cms_dir}/cryptominisat5Config.cmake" "")
file(WRITE "${cms_dir}/camada-cms-5.11.22.stamp" "")
file(WRITE "${CAMADA_DEPS_INSTALL_DIR}/lib/libcadical-cms.a" "old")
file(WRITE "${CAMADA_DEPS_INSTALL_DIR}/lib/libcadiback.a" "old")
file(WRITE "${CAMADA_DEPS_INSTALL_DIR}/lib/libabc-pic.a" "")
file(WRITE "${CAMADA_DEPS_INSTALL_DIR}/lib/cmake/STP/STPConfig.cmake" "")
foreach(old cadical cadiback cryptominisat_cadiback-src)
  file(WRITE "${CMAKE_BINARY_DIR}/_deps/${old}/old.a" "old")
endforeach()
file(REMOVE "${CAMADA_CADICAL_LIB}")
camada_setup_stp()
if(NOT EXISTS "${TEST_DIR}/cms-built" OR NOT EXISTS "${CAMADA_CADICAL_LIB}")
  message(FATAL_ERROR "Cached STP bypassed CMS/shared CaDiCaL migration")
endif()
file(READ "${CAMADA_DEPS_INSTALL_DIR}/lib/libcadiback.a" cadiback)
if(NOT cadiback STREQUAL "new"
   OR EXISTS "${CAMADA_DEPS_INSTALL_DIR}/lib/libcadical-cms.a")
  message(FATAL_ERROR "Old CadiBack/CaDiCaL installation survived")
endif()
camada_setup_stp()
# Discovery must migrate even when find_package would find the cached STP.
file(REMOVE "${TEST_DIR}/cms-built" "${cms_dir}/camada-cms.stamp")
include("${CMAKE_CURRENT_LIST_DIR}/../FindSTP.cmake")
if(NOT EXISTS "${TEST_DIR}/cms-built")
  message(FATAL_ERROR "STP discovery bypassed CMS migration")
endif()
message(STATUS "Dependency migration checks passed")
