name: MacOS Build
on: [push, pull_request]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
    - name: Install Dependencies
      run: brew install gmp cmake ninja python3 automake boost zlib bison flex z3 && pip3 install toml

      # Setup Catch2. TODO: replace it with https://github.com/marketplace/actions/continuous-benchmark
    - name: Setup Catch2
      run: git clone https://github.com/catchorg/Catch2.git && cd Catch2 && git reset --hard v2.13.2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF -GNinja && cd build && sudo ninja && sudo ninja install

      # Setup/cache Boolector
    - name: Cache Boolector
      id: cache-boolector
      uses: actions/cache@v2
      with:
        path: boolector-release
        key: ${{ runner.os }}-boolector

    - name: Setup boolector
      if: steps.cache-boolector.outputs.cache-hit != 'true'
      run: git clone https://github.com/boolector/boolector && cd boolector && git reset --hard 3.2.1 && ./contrib/setup-lingeling.sh && ./contrib/setup-btor2tools.sh && ./configure.sh --prefix $PWD/../boolector-release && cd build && make -j && make install

      # Setup SymFPU
    - name: Setup SymFPU
      run: git clone https://github.com/martin-cs/symfpu && cd symfpu && git reset --hard 8fbe139bf0071cbe0758d2f6690a546c69ff0053

      # Setup/cache MathSAT
    - name: Cache MathSAT
      id: cache-mathsat
      uses: actions/cache@v2
      with:
        path: mathsat
        key: ${{ runner.os }}-mathsat

    - name: Setup MathSAT
      if: steps.cache-mathsat.outputs.cache-hit != 'true'
      run: wget http://mathsat.fbk.eu/download.php?file=mathsat-5.6.3-darwin-libcxx-x86_64.tar.gz -O mathsat.tar.gz && tar xf mathsat.tar.gz && mv mathsat-5.6.3-darwin-libcxx-x86_64 mathsat && ln -s /usr/local/include/gmp.h mathsat/include/gmp.h && cp mathsat/lib/libmathsat.dylib /usr/local/lib && cp mathsat/lib/libmathsat.a /usr/local/lib

    - name: Setup CryptoMiniSAT
      run: wget -c https://github.com/msoos/cryptominisat/archive/5.8.0.zip && unzip 5.8.0.zip && cd cryptominisat-5.8.0 && mkdir build && cd build && cmake .. -GNinja -DCMAKE_INSTALL_PREFIX=$PWD/../../cryptominisat && ninja && ninja install

    - name: Setup MiniSAT
      run: git clone https://github.com/mikhailramalho/minisat-os-x.git && cd minisat-os-x && make config prefix=$PWD/../minisat && make -j install

      # Setup/cache STP
    - name: Setup STP
      continue-on-error: true
      run: git clone https://github.com/stp/stp.git && cd stp && git reset --hard 9a59a72e && mkdir build && cd build && cmake .. -GNinja -DCMAKE_INSTALL_PREFIX=$PWD/../../stp-release -DMINISAT_INCLUDE_DIR=$PWD/../../minisat/include -DMINISAT_LIBRARY=$PWD/../../minisat/lib/libminisat.a && ninja install

    - name: Setup Yices
      run: git clone https://github.com/SRI-CSL/yices2.git && cd yices2 && git reset --hard Yices-2.6.1 && autoreconf -fi && ./configure --prefix $PWD/../yices && make -j && make static-lib && make install && cp ./build/x86_64-apple-darwin*release/static_lib/libyices.a ../yices/lib
    - name: Install yices
      run: cp yices/lib/libyices.dylib /usr/local/lib && cp yices/lib/libyices.a /usr/local/lib

    - name: Configure Camada
      run: mkdir build && cd build && cmake .. -GNinja -DCAMADA_ENABLE_REGRESSION=On -DBUILD_SHARED_LIBS=OFF -DCAMADA_ENABLE_SOLVER_BOOLECTOR=ON -DSOLVER_BOOLECTOR_DIR=$PWD/../boolector-release -DCAMADA_ENABLE_SOLVER_MATHSAT=ON -DSOLVER_MATHSAT_DIR=$PWD/../mathsat -DCAMADA_ENABLE_SOLVER_STP=ON -DSOLVER_STP_DIR=$PWD/../stp-release -DCAMADA_ENABLE_SOLVER_YICES=ON -DSOLVER_YICES_DIR=$PWD/../yices -DCAMADA_ENABLE_SOLVER_Z3=ON -DSOLVER_Z3_DIR=$PWD/../z3 -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../release -DCMAKE_BUILD_TYPE=Debug
    - name: Build Camada
      run: cd build && ninja && ninja install
    - name: Run tests
      run: cd build/regression && ctest -j --output-on-failure --progress .

