name: MacOS CVC4 Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  build-cvc4:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
    - name: Install Dependencies
      run: brew install gmp cmake ninja python3 && pip3 install toml
    - name: Setup Catch2
      run: git clone https://github.com/catchorg/Catch2.git && cd Catch2 && git reset --hard v2.13.2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install
    - name: Setup CVC4
      run: git clone https://github.com/CVC4/CVC4.git && cd CVC4 && git reset --hard 1.8 && ./contrib/get-antlr-3.4 && ./contrib/get-symfpu && ./configure.sh --symfpu --symfpu-dir=../symfpu --python3 --optimized --prefix=../cvc4 --static --no-static-binary && cd build && make -j4 && make install
    - name: Configure CMake
      run: mkdir build && cd build && cmake .. -GNinja -DCAMADA_ENABLE_REGRESSION=On -DBUILD_SHARED_LIBS=OFF -DCAMADA_ENABLE_SOLVER_CVC4=ON -DSOLVER_CVC4_DIR=$PWD/../cvc4 -DSOLVER_CVC4_SYMFPU_DIR=$PWD/../CVC4/deps/install/include -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../release
    - name: Build Camada
      run: cd build && cmake --build . && cmake --install .
    - name: Run tests
      run: cd build/regression && ctest -j4 --output-on-failure --progress .

