name: MacOS Build
on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
    - name: Install Dependencies
      run: brew install gmp cmake ninja python3 automake boost zlib bison flex && pip3 install toml && pip3 install -r requirements.txt

      # Setup Catch2. TODO: replace it with https://github.com/marketplace/actions/continuous-benchmark
    - name: Setup Catch2
      run: git clone https://github.com/catchorg/Catch2.git && cd Catch2 && git reset --hard v2.13.2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF -GNinja && cd build && sudo ninja && sudo ninja install

      # Setup/cache dependencies
    - name: Cache deps
      id: cache-deps-v2
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-deps-v2

    - name: Setup Dependencies
      if: steps.cache-deps-v2.outputs.cache-hit != 'true'
      run: python3 ./scripts/get-deps.py -a

    - name: Configure Camada
      run: mkdir build && cd build && cmake .. -GNinja -DCAMADA_ENABLE_REGRESSION=On -DBUILD_SHARED_LIBS=OFF -DCAMADA_BOOLECTOR_ENABLE=ON -DCAMADA_CVC4_ENABLE=ON -DCAMADA_CVC4_SYMFPU_DIR=$PWD/../deps/src/cvc5-1.8/deps/install/include -DCAMADA_MATHSAT_ENABLE=ON -DCAMADA_STP_ENABLE=ON -DCAMADA_YICES_ENABLE=ON -DCAMADA_Z3_ENABLE=ON -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../release -DCMAKE_BUILD_TYPE=Debug

    - name: Build Camada
      run: cd build && ninja && ninja install

    - name: Run tests
      run: cd build/regression && ctest -j --output-on-failure --progress .

