name: Linux Build
on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install catch2 cmake linux-libc-dev ninja-build gperf && pip3 install toml && pip3 install -r requirements.txt

      # Setup/cache dependencies
    - name: Cache deps
      id: cache-deps-v5
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-deps-v5

    - name: Setup Dependencies
      if: steps.cache-deps-v5.outputs.cache-hit != 'true'
      run: python3 ./scripts/get-deps.py -a

    - name: Configure Camada
      run: mkdir build && cd build && cmake .. -GNinja -DCAMADA_ENABLE_REGRESSION=On -DBUILD_SHARED_LIBS=OFF -DCAMADA_BOOLECTOR_ENABLE=ON -DCAMADA_CVC5_ENABLE=ON -DCAMADA_MATHSAT_ENABLE=ON -DCAMADA_STP_ENABLE=ON -DCAMADA_YICES_ENABLE=ON -DCAMADA_Z3_ENABLE=ON -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../release -DCMAKE_BUILD_TYPE=Debug

    - name: Build Camada
      run: cd build && ninja && ninja install

    - name: Run tests
      run: cd build/regression && ctest -j --output-on-failure --progress .

