name: MacOS Yices Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  build-yices:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: brew install gmp ninja automake
    - name: Setup Catch2
      run: git clone https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install
    - name: Setup Yices 2
      run: git clone https://github.com/SRI-CSL/yices2.git && cd yices2 && git reset --hard Yices-2.6.1 && autoreconf -fi && ./configure --prefix $PWD/../yices && make -j4 && make static-lib && make install && cp ./build/x86_64-apple-darwin*release/static_lib/libyices.a ../yices/lib
    - name: Install yices
      run: cp yices/lib/libyices.dylib /usr/local/lib && cp yices/lib/libyices.a /usr/local/lib
    - name: Configure CMake
      run: mkdir build && cd build && cmake .. -GNinja -DCAMADA_ENABLE_REGRESSION=On -DBUILD_SHARED_LIBS=OFF -DCAMADA_ENABLE_SOLVER_YICES=ON -DSOLVER_YICES_DIR=$PWD/../yices -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../release
    - name: Build Camada
      run: cd build && cmake --build . && cmake --install .
    - name: Run tests
      run: cd build/regression && ctest -j4 --output-on-failure --progress .

