name: MacOS Z3 Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  build-z3:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: brew install cmake ninja z3
    - name: Setup Catch2
      run: git clone https://github.com/catchorg/Catch2.git && cd Catch2 && git reset --hard v2.13.2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install
    - name: Configure CMake
      run: mkdir build && cd build && cmake .. -GNinja -DCAMADA_ENABLE_REGRESSION=On -DBUILD_SHARED_LIBS=OFF -DCAMADA_ENABLE_SOLVER_Z3=ON -DSOLVER_Z3_DIR=$PWD/../z3 -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../release
    - name: Build Camada
      run: cd build && cmake --build . && cmake --install .
    - name: Run tests
      run: cd build/regression && ctest -j4 --output-on-failure --progress .

