name: MacOS Build
on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:

  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: brew install catch2 gmp cmake ninja automake boost zlib bison flex libtool pkg-config gettext texinfo doxygen z3

    - name: Configure Homebrew Environment
      run: |
        echo "CPPFLAGS=-I$(brew --prefix gmp)/include" >> $GITHUB_ENV
        echo "LDFLAGS=-L$(brew --prefix gmp)/lib" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$(brew --prefix gmp)/lib/pkgconfig:$(brew --prefix zlib)/lib/pkgconfig" >> $GITHUB_ENV

      # Setup/cache dependencies
    - name: Cache deps
      id: cache-deps-v6
      uses: actions/cache@v4
      with:
        path: |
          build/deps
          build/_deps
        key: ${{ runner.os }}-deps-v6

    - name: Configure Camada
      run: cmake -S . -B build -GNinja -DCAMADA_ENABLE_REGRESSION=ON -DBUILD_SHARED_LIBS=OFF -DCAMADA_DOWNLOAD_DEPENDENCIES=ALL -DCAMADA_SOLVER_BITWUZLA_ENABLE=ON -DCAMADA_SOLVER_CVC5_ENABLE=ON -DCAMADA_SOLVER_MATHSAT_ENABLE=ON -DCAMADA_SOLVER_STP_ENABLE=ON -DCAMADA_SOLVER_YICES_ENABLE=ON -DCAMADA_SOLVER_Z3_ENABLE=ON -DCMAKE_INSTALL_PREFIX:PATH=$GITHUB_WORKSPACE/release -DCMAKE_BUILD_TYPE=Debug

    - name: Build Camada
      run: cmake --build build -j1 --target install

    - name: Run tests
      run: ctest --test-dir build --output-on-failure -E "MathSAT"
