name: Camada Code Style

on: [push, pull_request]
jobs:

  # Check project with clang-format
  code-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install clang-tools-9
    - name: Run clang-format
      run: find src -iname *.h -o -iname *.c -o -iname *.cpp -o -iname *.hpp -iname *.hh | xargs clang-format -style=llvm -i
    - name: Throws error if changes were made
      run: git diff --exit-code

