on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build-linux:
    name: Build Linux Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake linux-libc-dev ninja-build gperf doxygen pkg-config libgmp-dev libmpfr-dev python3

    - name: Generate release
      run: python3 ./scripts/release.py

    - name: Create tarball
      run: tar -C release -czvf camada-linux-x64.tar.gz .

      # Upload asset
    - uses: actions/upload-artifact@v4
      with:
        name: release-linux
        path: ./camada-linux-x64.tar.gz

  build-macos:
    name: Build MacOS Release
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: brew install gmp cmake ninja automake boost zlib bison flex doxygen libtool pkg-config gettext texinfo python3 z3

    - name: Configure Homebrew Environment
      run: |
        echo "CPPFLAGS=-I$(brew --prefix gmp)/include" >> $GITHUB_ENV
        echo "LDFLAGS=-L$(brew --prefix gmp)/lib" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$(brew --prefix gmp)/lib/pkgconfig:$(brew --prefix zlib)/lib/pkgconfig" >> $GITHUB_ENV

    - name: Generate release
      run: python3 ./scripts/release.py

    - name: Create tarball
      run: tar -C release -czvf camada-macos-arm64.tar.gz .

      # Upload asset
    - uses: actions/upload-artifact@v4
      with:
        name: release-macos
        path: camada-macos-arm64.tar.gz

  create-release:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    steps:
    - name: Download Linux Build
      uses: actions/download-artifact@v4
      with:
        name: release-linux
        path: ./

    - name: Download Macos Build
      uses: actions/download-artifact@v4
      with:
        name: release-macos
        path: ./

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (Linux)
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./camada-linux-x64.tar.gz
        asset_name: camada-linux-x64.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release Asset (MacOS)
      id: upload-release-asset-macos
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./camada-macos-arm64.tar.gz
        asset_name: camada-macos-arm64.tar.gz
        asset_content_type: application/gzip
